
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  before_script:
    - echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$(printf "%s:%s" "teknologforeningen" "${CR_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "ghcr.io/teknologforeningen/tf-strapi:latest"
