version: "3"
services:
  db:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: strapi
      POSTGRES_DB: strapi
